name: CI/CD Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build and Test
        run: |
          npm install
          npm run build
          npm run test
          
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy to Production
        uses: appleboy/scp-action@v0.1.0 # Example action
        with:
          host: ${{ secrets.pranshu-pdf.vercel.app}}
          username: ${{ secrets.root}}
          key: ${{ secrets.NqjdD1UScDcsrATp6Q0FTkwEnaJB2p+9PqOHDFVDRfU }}
          target: /path/to/deploy
